Source/Project/WebBanGiay/WebBanGiay/Controllers/GiayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanGiayBLL;
using BanGiayBLL.BLL;

namespace WebBanGiay.Controllers
{
    public class GiayController : Controller
    {
        private GiayBLL giaybll = new GiayBLL();
        // GET: /Giay/
        public ActionResult Index()
        {
            //var giay = db.GIAY.Include(g => g.CHITIETSANPHAM).Include(g => g.LOAIGIAY);
            return View(giaybll.List());
        }

        // GET: /Giay/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAY giay = giaybll.Details(id);
            if (giay == null)
            {
                return HttpNotFound();
            }
            return View(giay);
        }

        //// GET: /Giay/Create
        //public ActionResult Create()
        //{
        //    ViewBag.MaGiay = new SelectList(db.CHITIETSANPHAM, "MaGiay", "MauSac");
        //    ViewBag.MaLoaiGiay = new SelectList(db.LOAIGIAY, "MaLoai", "TenLoai");
        //    return View();
        //}

        // POST: /Giay/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="MaGiay,MaLoaiGiay,TenGiay,HangSanXuat,Gia,GiaKhuyenMai,MoTa,HinhAnh")] GIAY giay)
        {
            if (ModelState.IsValid)
            {
                giaybll.Create(giay);
                return RedirectToAction("Index");
            }

            //ViewBag.MaGiay = new SelectList(db.CHITIETSANPHAM, "MaGiay", "MauSac", giay.MaGiay);
            //ViewBag.MaLoaiGiay = new SelectList(db.LOAIGIAY, "MaLoai", "TenLoai", giay.MaLoaiGiay);
            return View(giay);
        }

        // GET: /Giay/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAY giay = giaybll.Details(id);
            if (giay == null)
            {
                return HttpNotFound();
            }
            //ViewBag.MaGiay = new SelectList(db.CHITIETSANPHAM, "MaGiay", "MauSac", giay.MaGiay);
            //ViewBag.MaLoaiGiay = new SelectList(db.LOAIGIAY, "MaLoai", "TenLoai", giay.MaLoaiGiay);
            return View(giay);
        }

        // POST: /Giay/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="MaGiay,MaLoaiGiay,TenGiay,HangSanXuat,Gia,GiaKhuyenMai,MoTa,HinhAnh")] GIAY giay)
        {
            if (ModelState.IsValid)
            {
                giaybll.Edit(giay);
                return RedirectToAction("Index");
            }
            //ViewBag.MaGiay = new SelectList(db.CHITIETSANPHAM, "MaGiay", "MauSac", giay.MaGiay);
            //ViewBag.MaLoaiGiay = new SelectList(db.LOAIGIAY, "MaLoai", "TenLoai", giay.MaLoaiGiay);
            return View(giay);
        }

        // GET: /Giay/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GIAY giay = giaybll.Details(id);
            if (giay == null)
            {
                return HttpNotFound();
            }
            return View(giay);
        }

        // POST: /Giay/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            giaybll.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

Source/Project/WebBanGiay/WebBanGiay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="vi"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Thế Giới Giày Dép</title>
	<meta name="description" content="Trang web ban giay hang dau Viet Nam">
	<meta name="author" content="1012028_1012095">
	
    <!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== 
	<link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/responsive.css">
	<link rel='stylesheet' href="css/camera.css"> -->
	
	<!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="js/html5.js"></script>
	<![endif]-->
	
	<link href='./images/favicon.ico' rel='icon' type='image/x-icon'/>
    
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/js")
@Scripts.Render("~/bundles/jquery")

    
    <script>
        jQuery.noConflict(function(){
            jQuery('#camera_wrap').camera({
                height: '400px',
                loader: 'bar',
                pagination: false,
                thumbnails: true
            });
        });
	</script>
	
</head>
<body>
<!--------------Header--------------->
<header> 
	<div class="pagetop">
		<div class="wrap-pagetop">
			<div id="search">
				<div class="button-search"></div>
				<input type="text" value="Search..." onfocus="if (this.value == &#39;Search...&#39;) {this.value = &#39;&#39;;}" onblur="if (this.value == &#39;&#39;) {this.value = &#39;Search...&#39;;}">
			</div>
		</div>
	</div>
	<div class="wrap-header">
		<div id="logo"><a href="#"><img src="@Url.Content("~/images/logo.png")"/></a></div>
		<nav>
			<ul>
				<li class="current"><a href="index.html">Trang Chủ</a></li>			
				<li>@Html.ActionLink("Sản Phẩm","index","Giay")
				<li><a href="lienhe.html">Liên Hệ</a></li>
				<li><a href="dangnhap.html">Đăng Nhập</a></li>
			</ul>
		</nav>
	</div>
</header>

<!--------------Content--------------->
<section id="content">   
	<div class="feature">
		<div class="camera_wrap camera_magenta_skin" id="camera_wrap">
            <div data-thumb="images/slides/thumbs/1.jpg" data-src="images/slides/slide1.jpg">
                <div class="camera_caption fadeFromBottom">
                    Ho Ngoc Ha. <em>thoi trang mode thu he 15</em>
                </div>
            </div>
            <div data-thumb="images/slides/thumbs/2.jpg" data-src="images/slides/slide2.jpg">
                <div class="camera_caption fadeFromBottom">
                    Giay moi nhat, <em>loai giay cao co giay cho gai tan thoi</em>
                </div>
            </div>
            <div data-thumb="images/slides/thumbs/3.jpg" data-src="images/slides/slide3.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>Danh cho ong TYPN</em> 
                </div>
            </div>
			<div data-thumb="images/slides/thumbs/4.jpg" data-src="images/slides/slide4.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>Danh cho Ulsa Bol</em> (Nhanh nhu chop)
                </div>
            </div>
			<div data-thumb="images/slides/thumbs/5.jpg" data-src="images/slides/slide5.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>It's completely free</em> (even if a donation is appreciated)
                </div>
            </div>
			<div data-thumb="images/slides/thumbs/6.jpg" data-src="images/slides/slide6.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>Thoi trang Ha Noi mua xau no</em> (phien ban tu Han Quoc)
                </div>
            </div>
			<div data-thumb="images/slides/thumbs/7.jpg" data-src="images/slides/slide7.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>Mua lac</em> (Son la, Lai chau)
                </div>
            </div>
			<div data-thumb="images/slides/thumbs/8.jpg" data-src="images/slides/slide8.jpg">
                <div class="camera_caption fadeFromBottom">
                    <em>Doi dep phu nu dam dang</em> (Phu hop voi moi dia hinh)
                </div>
            </div>
        </div>
		<div style="clear:both; display:block; height:10px"></div>
	</div>
    @RenderBody()
	<div class="welcome">
		<p>Chào mừng quý khách đến với thế giới giày dép của chúng tôi</p>
	</div>
	<div class="zerogrid">		
		<div class="row block01">
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb1.jpg" class="grayscale"/><h2>Giày Thể Thao</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb2.jpg" class="grayscale"/><h2>Giày Buộc Dây</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb3.jpg" class="grayscale"/><h2>Giày Da Nam</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb4.jpg" class="grayscale"/><h2>Giày Công Sở</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb5.jpg" class="grayscale"/><h2>Dép Tổ Ong</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb6.jpg" class="grayscale"/><h2>Giày Đế Mềm</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb7.jpg" class="grayscale"/><h2>Giày Cưới</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb8.jpg" class="grayscale"/><h2>Giày Vải</h2></a>
				</article>
			</div>
			<div class="col-1-3">
				<article>
					<a href="blog.html"><img src="images/thumb9.jpg" class="grayscale"/><h2>Giày Buộc Dây</h2></a>
				</article>
			</div>
		</div>
	</div>
</section>
   
<!--------------Footer--------------->
<footer>
	<div class="zerogrid">
		<div class="row block02">
			<section class="col-1-3">
				<div class="heading"><h2>Giới Thiệu</h2></div>
				<div class="content">
					<p>Giày dép thương hiệu hàng đầu</p>
				</div>
			</section>
			<section class="col-1-3">
				<div class="heading"><h2>Phân Loại Giày</h2></div>
				<div class="content">
					<ul>
						<li><a href="http://www.zerotheme.com">Giày Thể Thao</a></li>
						<li><a href="http://www.zerotheme.com">Giày Vải</a></li>
						<li><a href="http://www.zerotheme.com">Giày Nữ</a></li>
					</ul>
				</div>
			</section>
			<section class="col-1-3">
				<div class="heading"><h2>Sản Phẩm Hot</h2></div>
				<div class="content">
					<div class="post">
						<img src="images/port1.jpg"/>
						<h4><a href="blog.html">giay moi nhat</a></h4>
						<p>100.000 VNĐ</p>
					</div>
					<div class="post">
						<img src="images/port2.jpg"/>
						<h4><a href="blog.html">ádfghj</a></h4>
						<p>100.000 VNĐ</p>
					</div>
					<div class="post">
						<img src="images/port3.jpg"/>
						<h4><a href="blog.html">ádfg</a></h4>
						<p>100.000 VNĐ</p>
					</div>
				</div>
			</section>
		</div>
	</div>
	<div class="copyright">
		<p>Copyright © 2014 - <a href="http://www.abc.com" target="_blank">Giaydep.com</a> by 1012028_1012095</p>
	</div>
</footer>
    @RenderSection("scripts", required: false)
</body></html>